[ml2]
type_drivers = flat,vlan,geneve
tenant_network_types = geneve
mechanism_drivers = ovn
extension_drivers = port_security,qos

[ml2_type_geneve]
vni_ranges = 1:65536

[ml2_type_vlan]
network_vlan_ranges = physnet1:100:200

[ovn]
ovn_nb_connection = tcp:10.8.132.194:6641,tcp:10.8.132.195:6641,tcp:10.8.132.196:6641
ovn_sb_connection = tcp:10.8.132.194:6642,tcp:10.8.132.195:6642,tcp:10.8.132.196:6642
ovn_nb_private_key = /etc/kolla/config/neutron/ovn_nb_cert.pem
ovn_nb_certificate = /etc/kolla/config/neutron/ovn_nb_cert.pem
ovn_nb_ca_cert = /etc/kolla/config/neutron/ovn_nb_ca_cert.pem
ovn_sb_private_key = /etc/kolla/config/neutron/ovn_sb_cert.pem
ovn_sb_certificate = /etc/kolla/config/neutron/ovn_sb_cert.pem
ovn_sb_ca_cert = /etc/kolla/config/neutron/ovn_sb_ca_cert.pem

[securitygroup]
enable_security_group = True
firewall_driver = openvswitch_firewall
